[WIP] Add NonEmptySet
fsprojects/FSharpPlus pull request #353
Opened 2020-09-08 09:04 UTC by cannorin

Close #342.

This PR implements `NonEmptySet` and `NonEmptyMap`.

2020-09-08 13:06 UTC, cannorin commented
Related: #351

2020-09-09 05:16 UTC, gusty requested changes

2020-09-09 05:16 UTC, gusty commented on src/FSharpPlus/Data/NonEmptyMap.fs
> +    let ofList (list : _ list) =
It would be nice to have `ofNonEmptyList` as it would be a safe operation.
Yet better, `ofNonEmptySeq` if we had it ;)

2020-09-12 11:57 UTC, wallymathieu commented on src/FSharpPlus/Data/NonEmptyMap.fs
> +        ofMap <!> m' : '``Functor<NonEmptyMap<'K, 'U>>``
if we look at the traversei implementation for `Map`, it seems like the return type does not need to be Map?

2020-09-12 12:25 UTC, wallymathieu commented on src/FSharpPlus/Data/NonEmptyMap.fs
> +        ofMap <!> m' : '``Functor<NonEmptyMap<'K, 'U>>``
For instance if I look at 
https://github.com/fsprojects/FSharpPlus/blob/1c5846a51a5083b94c12090e727ad6743b29c629/tests/FSharpPlus.Tests/General.fs#L1112-L1115

2020-09-12 13:03 UTC, wallymathieu commented on src/FSharpPlus/Data/NonEmptyMap.fs
> +        ofMap <!> m' : '``Functor<NonEmptyMap<'K, 'U>>``
Though it looks like you have wrap the result in option here, but it's the same type of structure inside

2020-09-16 07:06 UTC, cannorin commented
Should we add builders for them?

2020-09-16 07:09 UTC, gusty commented
I am not sure if we should. If we finally add `NonEmptySeq` we can add a builder for it which can be used as source for the `ofNonEmptySeq` methods and I think performancewise it will be the same.

2020-09-16 07:20 UTC, cannorin commented
Performed a rebase.

2020-09-17 07:12 UTC, gusty approved these changes
Great job !

2020-09-17 07:21 UTC, merged