Implement (try)FindLastSliceIndex
fsprojects/FSharpPlus pull request #581
Opened 2024-01-03 09:15 UTC by rzikm

Closes #574

I was not able to build the test project, so I rely on CI to run them.

2024-01-04 07:15 UTC, wallymathieu commented
@rzikm Hi! What kind of issues around running the tests do you have?

2024-01-05 06:44 UTC, gusty commented
@rzikm That's fine, I also rely mostly in CIs run. You can keep adding commits, I will squash in the end.

Also, if you want to run them locally do it in Release mode, I don't think they will compile in DEBUG mode due to an old F# compiler bug.

2024-01-05 10:12 UTC, gusty commented
> I also got snagged because there is more than one WrappedListD type and I added a function to only one of them. Maybe there is a room for internal cleanup?

AFAIK There's only one, which is in General.fs line 70

The main purpose of these types was to test overloads paths, but @wallymathieu recently added a better mechanism for it in #557 

Still these wrapper types are sometimes useful to perform some tests as they are user-defined classes.

Independently from that, cleanups are always welcome, but then you have to consider either doing them in a separate PR or in a separate commit and then squash all the other unrelated commits.

My advice is a separate commit so you can draft it first and we can give early feedback.

BTW: when doing a separate PR or opening a new issue please mention me because somehow I never managed to get notifications for them until I participate.

2024-01-05 10:30 UTC, rzikm commented
> AFAIK There's only one, which is in General.fs line 70

The other one is in https://github.com/fsprojects/FSharpPlus/blob/54ffdcc9bf2638bca3d270e35c4e3de022ecc7d0/tests/FSharpPlusFable.Tests/FSharpTests/General/Util.fs#L67

2024-01-05 10:47 UTC, gusty commented
Oh, but those are Fable tests.
Fable tests are independent, they have their own set of wrappers.

We can unify some stuff, but sometimes it gets complicated.

2024-01-06 07:35 UTC, gusty commented
This seems to be ready to merge. The failure in appveyor is a transient one.

2024-01-06 18:19 UTC, gusty requested changes
Looks good to me. Just 2 nits.
In fact, there's room for optimizations by using ListCollector and possibly ArrayCollector, but to be fair, the same would apply to `findSliceIndex`, so it's better to leave both for a separate PR.

Thanks for this contribution !

2024-01-06 18:19 UTC, gusty commented on src/FSharpPlus/Internals.fs
> +    module internal Q=
```suggestion
    module internal Q =
```

2024-01-06 18:19 UTC, gusty commented on src/FSharpPlus/Internals.fs
> +            match dequeued with | Some v -> v | None -> failwith "Empty queue!"
```suggestion
            match dequeued with | Some v -> v | None -> invalidOp "Empty queue!"
```

2024-01-06 22:26 UTC, gusty approved these changes

2024-01-06 23:49 UTC, merged